[build]
  command = "next build"
  publish = ".next"

  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "DB_PROVIDER,AUTH_URL,AUTH_SECRET,NEXTAUTH_SECRET,NEXTAUTH_URL,SSO_FEATURE_FLAG,EMAIL_FEATURE_FLAG,GMAIL_USER,GMAIL_APP_PASSWORD,SUPABASE_URL,NEXT_PUBLIC_SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,NEXT_PUBLIC_SITE_URL,NEXT_PUBLIC_BASE_URL,SMTP_HOST,LOCAL_STORAGE_PATH,NEXT_PUBLIC_SUPABASE_ANON_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
